# Generated by Django 6.0 on 2025-12-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=50)),
                ('website', models.URLField(help_text='The website of the publisher')),
                ('email', models.EmailField(help_text='The email of the publisher', max_length=254)),
            ],
        ),
    ]
